@startuml

' === ACTEURS ===
actor Malak as "Malak (Utilisatrice)" #87CEFA
actor Hakim as "Hakim (Editeur)" #FFFF99

' === CAS D'UTILISATION PUBLIC ===
usecase "Consulter les articles" as UC1
usecase "Lire un article" as UC2

' === CAS ADMIN/EDITEUR ===
usecase "Créer des articles" as UC3

' === RELATIONS ===
Malak -- UC1
Malak -- UC2

Hakim -- UC1
Hakim -- UC2
Hakim -- UC3

@enduml
